
export const PRODUCTS_MOCK = [
    { title: "Test", imageUrl: "url...", url:"url..."},
    { title: "Test2", imageUrl: "url...", url:"url..."},
    { title: "Test3", imageUrl: "url...", url:"url..."},
    { title: "Test4", imageUrl: "url...", url:"url..."},
    { title: "Test5", imageUrl: "url...", url:"url..."},
    { title: "Test6", imageUrl: "url...", url:"url..."},
    { title: "Test7", imageUrl: "url...", url:"url..."},
    { title: "Test8", imageUrl: "url...", url:"url..."},
    { title: "Test9", imageUrl: "url...", url:"url..."},
    { title: "Test10", imageUrl: "url...", url:"url..."},
    { title: "Test11", imageUrl: "url...", url:"url..."},
    { title: "Test12", imageUrl: "url...", url:"url..."},
    { title: "Test13", imageUrl: "url...", url:"url..."},
    { title: "Test14", imageUrl: "url...", url:"url..."},
    { title: "Test15", imageUrl: "url...", url:"url..."},
    { title: "Test16", imageUrl: "url...", url:"url..."},
    { title: "Test17", imageUrl: "url...", url:"url..."},
    { title: "Test18", imageUrl: "url...", url:"url..."},
    { title: "Test29", imageUrl: "url...", url:"url..."},
    { title: "Test20", imageUrl: "url...", url:"url..."},
];